import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { ThemeProvider } from '@/store/ThemeContext'
import Navbar from "@/components/ui/Navbar";
import "@/styles/globals.scss";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GS Dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black dark:bg-gray-900 dark:text-white transition-colors pt-16 h-full flex flex-col overflow-hidden`}
      >
        <ThemeProvider>
          <Navbar />
          <main id="main-content" className="flex-1 overflow-y-auto p-4">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
